# Generated by Django 3.1.1 on 2022-08-20 13:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.EmailValidator])),
                ('interests', models.CharField(blank=True, help_text='<small class="disabled float-right">max char 200</small>', max_length=200, null=True)),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='media/author_profile')),
                ('thought', models.CharField(blank=True, help_text="<small class='float-right'>max length 100</small>", max_length=100, null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='<small class="float-right">max char 200</small>', null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='<small class="float-right">max char 200</small>', null=True)),
                ('github_url', models.URLField(blank=True, help_text='<small class="float-right">max char 200</small>', null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='<small class="float-right">max char 200</small>', null=True)),
                ('notification_as_read', models.DateTimeField(default=datetime.datetime.now)),
                ('followers', models.ManyToManyField(blank=True, related_name='follow_to', to='accounts.UsersDetail')),
                ('username', models.OneToOneField(blank=True, help_text='<small class="disabled">Must be an unique <strong>Username</strong></small>', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
