# Generated by Django 3.1.1 on 2022-08-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_link', models.URLField(blank=True, max_length=500, null=True)),
                ('shorter_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
