# Generated by Django 3.1.1 on 2022-08-20 13:56

import ckeditor_uploader.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('selected_ans', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('ans_given_by', models.ManyToManyField(blank=True, related_name='ans_by_user', to='accounts.UsersDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('a_given', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qes_ans.answerby')),
                ('dis_like_by', models.ManyToManyField(blank=True, related_name='discussion_like_by', to='accounts.UsersDetail')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAsked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('qes_asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qes_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('total_likes', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('dis_like_by', models.ManyToManyField(blank=True, related_name='discussion_reply_like_by', to='accounts.UsersDetail')),
                ('dis_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dis_reply_to_user', to='accounts.usersdetail')),
                ('discuss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qes_ans.discussion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usersdetail')),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='q_asked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qes_ans.questionasked'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usersdetail'),
        ),
        migrations.AddField(
            model_name='answerby',
            name='q_asked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qes_ans.questionasked'),
        ),
    ]
